### ISSUE TITLE
difference with caml-inspect ?

### ISSUE THREAD

**Issue by zoggy** [Gbury/ocaml-memgraph#1]
Hello,

In case you were not aware of it, [caml-inspect](http://krohrer.github.io/caml-inspect/) seems to do almost the same as ocaml-memgraph. And by the way, I use it in a document for an [OCaml course](http://form-ocaml.forge.ocamlcore.org/modules/repr.html). 

Do you have precise needs or ideas to implement ?

**Comment by Gbury** [comment]
The idea behind ocaml-memgraph was to have some fun, and possibly have a tool to show beginners how the values in ocaml were represented in the memory.
I didn't know about inspect, but indeed, it pretty much does the same thing.

**Comment by Gbury** [comment]
Sorry for the (veeeeery long) delay. I looked a bit more detail into `caml-inspect`, and I'd say the main difference is that `memgraph` has a structured type to represent the memory graph of ocaml values (and has functions to create these representation), whereas I couldn't find it for `caml-inspect`, which seems to mainly have its `dot` creating functions that operate on arbitrary ocaml values. In that sense, `memgraph` might be easier to use for other things than to output `dot` (i.e. either to output to another format, or to write some analysis of memory values in pure ocaml).
